FROM tensorflow/tensorflow:2.12.0-gpu

ARG BUILD_DATE
ENV PORT 8888

LABEL org.opencontainers.image.authors="rinconyanezd@gmail.com" \
        org.opencontainers.image.vendor="Diego, Rincon-Yanez" \
        org.opencontainers.image.title="Tensorflow GPU Jupyter" \
        org.opencontainers.image.created=$BUILD_DATE \
        org.opencontainers.image.version="2.9.3" \
        org.opencontainers.image.revision="1.0" \
        org.opencontainers.image.url="https://github.com/d1egoprog/docker-tensorflow-gpu-jupyter" \
        org.opencontainers.image.documentation="https://github.com/d1egoprog/docker-tensorflow-gpu-jupyter" 

RUN apt-get -y update && apt-get -y install git

RUN apt-get update && apt-get install -y openjdk-8-jdk-headless

USER root

WORKDIR /root

RUN wget https://dlcdn.apache.org/spark/spark-3.4.1/spark-3.4.1-bin-hadoop3.tgz

RUN tar xzvf spark-3.4.1-bin-hadoop3.tgz

RUN mv spark-3.4.1-bin-hadoop3 /opt/spark-3.4.1

RUN ln -s /opt/spark-3.4.1 /opt/spark




RUN adduser jupyter

USER jupyter

ENV SPARK_HOME="/opt/spark"
ENV PATH="${PATH}:${SPARK_HOME}/bin:/home/jupyter/.local/bin"



WORKDIR /home/jupyter

RUN mkdir /home/jupyter/data; mkdir /home/jupyter/notebooks; mkdir /home/jupyter/tutorials

COPY requirements.txt /home/jupyter/requirements.txt
COPY tests/env_preparation.ipynb /home/jupyter/ 
COPY tests/gpu_check.ipynb /home/jupyter/



RUN python3 -m pip install --no-cache --upgrade setuptools pip

RUN pip install jupyter && pip install jupyterlab
 

RUN pip install -r requirements.txt


ENV PYSPARK_DRIVER_PYTHON="jupyter"
ENV PYSPARK_DRIVER_PYTHON_OPTS="notebook"

EXPOSE $PORT

ENTRYPOINT ["/home/jupyter/.local/bin/jupyter", "lab","--ip=0.0.0.0","--allow-root"]
