name: CI/CD projet7

# Controls when the workflow will run
on:
  # Activates the workflow; then there is a push to the main or master branch
  push:
    paths:
      - projet7/**
    branches: [main, master]
    
# A workflow run consists of one or more jobs that can be executed either sequentially or concurrently.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd projet7/api
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          cd projet7/api
          pytest
